spring.application.name=todos-rest

spring.datasource.url=jdbc:mysql://localhost:3307/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

#JWT

spring.jwt.secret=8d58ac86e7621090056e99f525dd7b17dc5f128017c5d1273a0f121bd1d918d0
spring.jwt.expiration=900000
